### ISSUE TITLE
JHU data format is changing 

### ISSUE THREAD

**Issue by valeriupredoi** [valeriupredoi/COVID-19_LINEAR#7]
https://github.com/CSSEGISandData/COVID-19/issues/1250

**Comment by cipriancraciun** [comment]
Hi!  I've taken a look at your maps and found your projections interesting.

Anyway, given that the JHU dataset is constantly changing, I've derived myself the JHU (and NY Times and ECDC) datasets into a common format (available in JSON, TSV, SQL for now), that I update multiple times a day, after the original data sources are updated:

https://github.com/cipriancraciun/covid19-datasets

So I thought that it might be helpful to you, especially since I've taken care of proper country / province normalization and attribution, summation of provinces, etc.  (BTW, I also have augmented the dataset with population and yearly death rate per million people from the CIA Factbook dataset.)

In case you have any questions, don't hesitate to open an issue on my repository, or reply here.

**Comment by valeriupredoi** [comment]
cheers muchly @cipriancraciun - I'll defo head there if the JHU data keeps changing like this
