### ISSUE TITLE
Argentina

### ISSUE THREAD

**Issue by abedacarratz** [valeriupredoi/COVID-19_LINEAR#9]
Hi Valeriu, 

Salut :)

I noticed there are no countries in Latin America plotted. I think it may be interesting to compare Argentina and Mexico. Both countries reported their first cases at the end of February, and have had a similar number of cases reported for a while, but Argentina is in quarantine (people are in mandated home isolation) since March 20 whereas in Mexico there have hardly been any restrictions. Happy to help if you have any issues locating data in Spanish. 

Ana

**Comment by valeriupredoi** [comment]
hi @abedacarratz cheers for raising this! here is [Argentina](https://github.com/valeriupredoi/COVID-19_LINEAR/blob/master/country_plots/COVID-19_LIN_Argentina.png) and [Argentina simulated real cases](https://github.com/valeriupredoi/COVID-19_LINEAR/blob/master/country_plots/COVID-19_LIN_Argentina_SIM_CASES.png) and [Mexico](https://github.com/valeriupredoi/COVID-19_LINEAR/blob/master/country_plots/COVID-19_LIN_Mexico.png) and [Mexico simulated real cases](https://github.com/valeriupredoi/COVID-19_LINEAR/blob/master/country_plots/COVID-19_LIN_Mexico_SIM_CASES.png) -- interestingly Mexico's climb rate of 21% for reported cases is slower than Argentina's 26% but the reported cases are a wildly unreliable indicator: death rate of 12% in Argentina vs 29% in Mexico so that means surely there are a lot more cases in Mexico than they report - in fact, if you look at my simulation plots, for a death fraction of 1% there are about 2500 predicted real cases in Argentina on the last day of data (25th March) vs the predicted 9000 for Mexico for the same fraction. Hope this helps :beer:

**Comment by abedacarratz** [comment]
Thanks so much! Such is life. Hope you're taking good care of yourself, keep on rocking.

**Comment by valeriupredoi** [comment]
much appreciated and you too!!
